export const ADD_PRODUCT = "ADD_PRODUCT"
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR"

export const START_PRODUCTS_DOWNLOAD = "START_PRODUCTS_DOWNLOAD"
export const PRODUCTS_DOWNLOAD_SUCCESS = "PRODUCTS_DOWNLOAD_SUCCESS"
export const PRODUCTS_DOWNLOAD_ERROR = "PRODUCTS_DOWNLOAD_ERROR"

export const GET_PRODUCT_DELETE = "GET_PRODUCT_DELETE"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR"

export const GET_PRODUCT_EDIT = "GET_PRODUCT_EDIT"
export const START_PRODUCT_EDIT = "START_PRODUCT_EDIT"
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS"
export const EDIT_PRODUCT_ERROR = "EDIT_PRODUCT_ERROR"

export const SHOW_ALERT = "SHOW_ALERT"
export const HIDE_ALERT = "HIDE_ALERT"
